project:
  type: website
  output-dir: docs
  
website: 
  title: "meganvoss.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Resume.qmd
      - Projects.qmd

format:
  html:
    theme: sandstone
    linkcolor: "#9045db"   
    css: styles.css
    toc: true
    toc-location: right

editor: visual

